### ISSUE TITLE
Fails to build libtool

### ISSUE THREAD

**Issue by rainerkohlberger** [deepmind/spiral#3]
Hi,
python3 setup.py develop --user fails at building with the following output. Any hints? Thanks

```
[  0%] Performing build step for 'libmypaint'
Making all in .
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/local/include -I/usr/local/include/json-c -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush.lo -MD -MP -MF .deps/mypaint-brush.Tpo -c mypaint-brush.c  -fPIC -DPIC -o .libs/mypaint-brush.o
mypaint-brush.c: In function 'mypaint_brush_new':
mypaint-brush.c:133:26: error: 'FALSE' undeclared (first use in this function)
     self->print_inputs = FALSE;
                          ^
mypaint-brush.c:133:26: note: each undeclared identifier is reported only once for each function it appears in
mypaint-brush.c:142:29: error: 'TRUE' undeclared (first use in this function)
     self->reset_requested = TRUE;
                             ^
mypaint-brush.c: In function 'mypaint_brush_reset':
mypaint-brush.c:225:29: error: 'TRUE' undeclared (first use in this function)
     self->reset_requested = TRUE;
                             ^
mypaint-brush.c: In function 'mypaint_brush_stroke_to':
mypaint-brush.c:961:31: error: 'FALSE' undeclared (first use in this function)
       self->reset_requested = FALSE;
                               ^
mypaint-brush.c:980:14: error: 'TRUE' undeclared (first use in this function)
       return TRUE;
              ^
mypaint-brush.c: In function 'obj_get':
mypaint-brush.c:1100:44: error: 'TRUE' undeclared (first use in this function)
         && (obj_out ? (*obj_out != NULL) : TRUE);
                                            ^
mypaint-brush.c: In function 'update_brush_setting_from_json_object':
mypaint-brush.c:1120:16: error: 'FALSE' undeclared (first use in this function)
         return FALSE;
                ^
mypaint-brush.c:1167:12: error: 'TRUE' undeclared (first use in this function)
     return TRUE;
            ^
mypaint-brush.c: In function 'update_brush_from_json_object':
mypaint-brush.c:1177:16: error: 'FALSE' undeclared (first use in this function)
         return FALSE;
                ^
mypaint-brush.c:1193:28: error: 'TRUE' undeclared (first use in this function)
     gboolean updated_all = TRUE;
                            ^
mypaint-brush.c: In function 'mypaint_brush_from_string':
mypaint-brush.c:1227:16: error: 'FALSE' undeclared (first use in this function)
         return FALSE;
                ^
Makefile:724: recipe for target 'mypaint-brush.lo' failed
make[5]: *** [mypaint-brush.lo] Error 1
Makefile:834: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:592: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/libmypaint.dir/build.make:114: recipe for target 'libmypaint-prefix/src/libmypaint-stamp/libmypaint-build' failed
make[2]: *** [libmypaint-prefix/src/libmypaint-stamp/libmypaint-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/libmypaint.dir/all' failed
make[1]: *** [CMakeFiles/libmypaint.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    "build_ext": CMakeBuildExt,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 44, in run
    self.build_extension(ext)
  File "setup.py", line 48, in build_extension
    self.build_cmake(ext)
  File "setup.py", line 73, in build_cmake
    cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 2.
```

**Comment by amirsaeidy** [comment]
same problem here

**Comment by ddtm** [comment]
Not sure why this happens but maybe this thread could help (they discuss a very similar problem): https://www.linuxquestions.org/questions/slackware-14/libmypaint-on-slackware-current-4175622706

**Comment by ddtm** [comment]
I added a link to a pre-built Docker image to README. This should allow running the agent on any machine.
